# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  # A parameter per package
  run-create-and-destroy:
    type: boolean
    default: false
  run-create-and-destroy-azure:
    type: boolean
    default: false
  run-destroy-gcp-env:
    type: boolean
    default: false
  run-destroy-aws-env:
    type: boolean
    default: false
  run-destroy-all-envs:
    type: boolean
    default: false
  run-ci:
    type: boolean
    default: false
  run-create-destroy-local:
    type: boolean
    default: false
  run-service-mesh-e2e:
    type: boolean
    default: false
  test-aws-lambda:
    type: boolean
    default: false
  run-release-vs-stable:
    type: boolean
    default: false
  test-aws-dns:
    type: boolean
    default: false
  run-destroy-aws-dns-false:
    type: boolean
    default: false
  run-destroy-aws-dns-true:
    type: boolean
    default: false
  test:
    type: boolean
    default: false
  ci-use-diff-env:
    type: boolean
    default: false
  ci-env-name:
    type: string
    default: 'env-ci'
  ci-env-region-aws:
    type: string
    default: 'us-east-2'
  ci-env-region-gcp:
    type: string
    default: 'us-central1'
  run-opta-terraform-generate-test:
    type: boolean
    default: false

orbs:
  terraform: circleci/terraform@3.0.0
  codecov: codecov/codecov@3.1.1
  aws-cli: circleci/aws-cli@2.0
  kubernetes: circleci/kubernetes@0.12.1
  helm: circleci/helm@1.2.0
  gcp-cli: circleci/gcp-cli@2.4.0
  azure-cli: circleci/azure-cli@1.2.0